import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Next.js Starter",
  description: "Generated by EunSeong",
};

// Link 컴포넌트 장점:
// 1. Link 컴포넌트에 마우스를 올렸을 때, 해당 페이지의 내용을 미리 로딩하여 보여줍니다.
// 2. 이미 로딩된 페이지는 다시 로딩하지 않고, 캐싱하여 보여줍니다.
// -> Single Page Application(SPA)의 장점을 가지고 있습니다.
export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <h1><Link herf="/">WEB</Link></h1> 
        <ol>
          <li><Link href="/html">HTML</Link></li>
          <li><Link href="/css">CSS</Link></li>
          <li><Link href="/js">JavaScript</Link></li>
        </ol>
        {children}
        <ul>
          <li><Link href="/create">create</Link></li>
          <li><Link href="/update">update</Link></li>
          <li><input type="button" value="delete" /></li>
        </ul>
      </body>
    </html>
  );
}
